window.ENGLISH_BANK=[
["基本","Tell me about yourself.","請自我介紹。","看你能否用60秒說出職涯主線。","I graduated with a degree in Digital Media Design. I started in video production, later became a team leader, and then moved into digital advertising for about two and a half years. I now work in marketing at MyCard. These experiences made me want to strengthen my research and strategic thinking skills.","我畢業於數位媒體設計系，從影音製作與主管經驗，走到約兩年半數位廣告，目前在 MyCard 做行銷。這些經驗讓我希望補強研究與策略思考能力。","Why did you change your career direction?","Each move added a new layer to my skills: creative communication, data-driven decisions, and business thinking.","為什麼轉換職涯？每次轉換都增加一層能力：創意溝通、數據決策與商業思考。"],
["基本","Why do you want to pursue a master's degree?","為什麼想讀碩士？","區分工作學習與研究訓練。","Work taught me how to solve practical problems, but experience alone cannot always explain why a strategy works or whether it will work in another situation. I want stronger research and management skills so I can make more systematic decisions.","工作教我處理實務問題，但經驗本身不一定能解釋策略為何有效或能否套用到其他情境，因此我想補強研究與管理能力。","Why can't you learn this at work?","Work solves immediate problems. Graduate study trains me to define questions, test assumptions, and evaluate evidence systematically.","為什麼不能在工作學？工作解決當下問題；研究所訓練定義問題、檢驗假設與證據。"],
["基本","Why do you want to study now?","為什麼現在讀？","確認不是逃避工作。","I now have experience in creative production, digital advertising, and marketing. I have clearer questions from real work, so I believe this is the right time to study them more deeply.","我已有創意、廣告與行銷經驗，也形成更清楚的實務問題，所以現在是深入學習的適合時點。","Why not wait a few more years?","I want to build stronger research skills before moving further into strategic roles.","為什麼不再等？我希望在往策略角色前先建立研究能力。"],
["校系","Why did you apply to our program?","為什麼申請本所？","考古常見校系適配題，正式面試要換成該校具體內容。","I am looking for a program that can strengthen both my research skills and my understanding of management. My background is mainly in creative work, advertising, and marketing, so I want systematic training in research methods, consumer behavior, and strategic decision-making.","我希望同時補強研究能力與管理視角。我的背景在創意、廣告與行銷，因此希望系統學習研究方法、消費者行為與策略決策。","Which area interests you most?","I am especially interested in research methods, consumer behavior, marketing strategy, and data-driven decision-making.","最有興趣的領域？研究方法、消費者行為、行銷策略與數據決策。"],
["校系","What can you contribute to our program?","你能為本所帶來什麼？","不能只說努力。","I can bring practical experience from creative production, digital advertising, data analysis, and marketing planning. I can share how creative ideas, performance data, and business goals interact in real projects.","我能帶入創意製作、數位廣告、數據分析與行銷企劃經驗，分享創意、成效數據與商業目標如何在實務中互相影響。","What can you contribute academically?","I am still developing my academic skills, but I can bring practical questions and industry perspectives that can be examined through research.","學術上能貢獻什麼？帶入值得研究的實務問題與產業視角。"],
["校系","Why should we admit you?","為什麼要錄取你？","壓力版適配題。","I have experience across creative work, advertising, and marketing, and I have a clear reason for returning to school. I also understand that practical experience is not the same as research ability, so I know what I still need to learn.","我橫跨創意、廣告與行銷，也有清楚進修理由；同時知道實務經驗不等於研究能力，清楚自己還要補什麼。","What makes you different?","My advantage is the combination of creative, data, and cross-functional experience.","你和別人差在哪？創意、數據與跨部門經驗的組合。"],
["研究","What is your research topic?","你的研究題目是什麼？","要能白話說研究。","My research focuses on whether different types of members respond differently to different relationship communication strategies, and how this may influence their intention to stay engaged.","我的研究關注不同類型會員是否對不同關係溝通策略產生不同反應，以及是否影響持續參與意向。","Can you explain it more simply?","I want to know whether different members need different communication strategies instead of using the same approach for everyone.","可以更簡單嗎？我想知道不同會員是不是需要不同溝通方式。"],
["研究","Why did you choose this topic?","為什麼選這題？","連結工作觀察與一般化問題。","My current work involves member campaigns. I noticed that companies often use similar messages for members with different levels of engagement. This made me interested in whether different members may need different relationship strategies.","我目前接觸會員活動，注意到不同參與程度的會員常收到類似溝通，因此想研究不同會員是否需要不同關係策略。","Is this only a company problem?","No. My work inspired the question, but I want to examine a more general relationship between engagement, strategy, and continued participation.","只是公司問題嗎？不是，工作提供靈感，但研究的是較一般化的變項關係。"],
["研究","What are your independent and dependent variables?","自變項與依變項？","研究方法基本題。","The dependent variable is members' intention to continue participating. Key explanatory factors include existing participation patterns and relationship strategies. The exact operational definitions still need to be refined through the literature.","依變項是會員持續參與意向；主要解釋因素包括既有參與型態與關係策略，正式操作化仍需依文獻收斂。","Why not define them now?","I do not want to define an academic construct only from my work experience. I need to confirm theory and established measures first.","為何不現在定死？不能只靠工作直覺定義學術構念。"],
["研究","Why do you need an experiment?","為什麼需要實驗？","理解問卷與實驗差異。","A survey can show relationships, but it is limited for causal inference. A scenario experiment can manipulate the communication strategy and compare responses under more controlled conditions.","問卷可看關聯但因果推論有限；情境實驗可操弄策略，在較受控制條件下比較反應。","What if it is too difficult?","I would adjust the scope based on feasibility and my advisor's guidance. Research quality is more important than forcing a two-stage design.","太難怎麼辦？依可行性與教授建議收斂，不硬做。"],
["研究","What if your hypothesis is not supported?","假設不成立怎麼辦？","經典研究壓力題。","I would first check the measurement, sample, manipulation, and analysis. If the design is sound, an unsupported hypothesis is still meaningful because the relationship may be weaker or more context-dependent than expected.","先檢查測量、樣本、操弄與分析；若設計合理，不支持假設仍可能表示關係較弱或受情境限制。","Would you change the analysis until it becomes significant?","No. The analysis should follow the research question and design.","會不會一直換分析做到顯著？不會，分析應依研究問題與設計。"],
["研究","What is the biggest limitation of your study?","最大研究限制？","看是否知道結論邊界。","Possible limitations include sampling bias, self-reported intention instead of actual behavior, and the artificial nature of a scenario experiment. I would not make claims beyond what the design can support.","可能限制包括抽樣偏誤、自陳意向不等於實際行為，以及情境實驗的人工性；不會過度推論。","Does that make the study less valuable?","No. A good study needs to answer a clear question and state its boundaries honestly.","這樣研究還有價值？有，重點是清楚回答問題並界定邊界。"]
];