window.ENGLISH_BANK.push(
["工作","What do you do at MyCard?","你在 MyCard 做什麼？","工作考古題，要說出思考而非清單。","I am involved in marketing proposals, member campaign planning, game-related projects, payment promotions, and post-campaign analysis. I now need to think more about the whole customer journey and how different campaign elements work together.","我參與行銷提案、會員活動、遊戲相關專案、金流活動與結案分析，也更需要思考完整顧客旅程與活動元素如何配合。","What have you learned from this role?","I learned to think beyond a single channel and consider member behavior, incentives, communication, and business goals together.","學到什麼？不只看單一渠道，而是一起考慮會員行為、誘因、溝通與商業目標。"],
["工作","What did you learn from digital advertising?","廣告投放教會你什麼？","把操作提升到決策能力。","Digital advertising taught me how to break down performance problems, test assumptions, allocate budgets, and make decisions based on evidence. It also taught me that data is useful only when the tracking and context are reliable.","數位廣告教我拆解成效問題、測試假設、分配預算與依證據決策，也讓我知道資料必須建立在可靠追蹤與情境上。","Is ROAS enough to evaluate a campaign?","No. We also need to consider objectives, attribution, scale, incremental impact, and long-term value.","ROAS夠嗎？還要看目標、歸因、規模、增量與長期價值。"],
["工作","Tell me about your leadership experience.","談談你的領導經驗。","主管經驗常見題。","When I was a team leader in video production, I learned that leadership is not about doing everything myself. I had to clarify standards, assign tasks, track progress, give feedback, and help the team handle unexpected problems.","擔任影音主管時，我學到領導不是全部自己做，而是釐清標準、分工、追蹤進度、給回饋並處理突發問題。","How would you handle an underperforming team member?","I would first identify whether the problem comes from unclear expectations, skills, resources, or motivation.","部屬表現不好？先判斷標準、能力、資源或動機是哪個問題。"],
["工作","Tell me about a failure or mistake.","說一個失敗或錯誤。","行為題，不能用假缺點。","I would explain a real case where my judgment was incomplete: what I missed, what impact it caused, how I corrected it, and what process I changed afterward.","我會說一個真正判斷不完整的案例：漏看什麼、造成什麼影響、如何修正，以及之後改了什麼流程。","What would you do differently now?","I would add a clearer checkpoint before execution and confirm key assumptions earlier.","重來會怎麼做？增加前置檢查並更早確認關鍵假設。"],
["工作","How do you handle disagreement with your manager?","和主管意見不同怎麼辦？","向上溝通題。","I first try to understand the manager's goal and constraints. Then I explain my concern with data, risks, or an alternative plan. If the final decision is different, I support it and track the result for future learning.","先理解主管目標與限制，再用數據、風險或替代方案表達；最終決策不同就配合並追蹤結果。","What if you were right?","The goal is not to prove I was right. I would use the result to improve the next decision.","如果證明你對？重點不是輸贏，而是改善下一次決策。"],
["職涯","What are your future career goals?","未來職涯目標？","學位與職涯連結。","In the short term, I want to deepen my skills in marketing strategy, consumer insight, and data-driven decision-making. In the longer term, I hope to take on broader strategic responsibilities and connect creative ideas, data, and business decisions.","短期深化行銷策略、消費者洞察與數據決策；長期承擔更完整策略責任，串起創意、數據與商業決策。","Do you want to become a manager?","A management title is not my only goal. I care more about taking responsibility for higher-level decisions.","一定要當主管？職稱不是唯一目標，更在意承擔更高層次決策。"],
["職涯","Where do you see yourself in five years?","五年後的你？","不能只說成功。","In five years, I hope to have more responsibility for marketing strategy and consumer insight, and to use research and data more confidently in business decisions.","五年後希望在行銷策略與消費者洞察承擔更多責任，也能更有信心運用研究與數據決策。","What skill do you need most?","I need stronger research design and analytical skills.","最需要什麼能力？更扎實的研究設計與分析。"],
["議題","How do you think AI will change marketing?","AI會如何改變行銷？","行銷議題題。","AI can reduce the time needed for content production, data organization, and early analysis. But when content becomes easier to produce, human judgment becomes more important. Marketers still need to define the right problem, understand consumers, protect brand consistency, and validate results.","AI能降低內容產製、資料整理與初步分析時間，但產出越容易，人類判斷越重要；行銷人仍需定義問題、理解消費者、維持品牌一致性與驗證結果。","Will AI replace marketers?","It may replace repetitive tasks, but it increases the value of strategic judgment and problem definition.","AI會取代行銷人？可能取代重複任務，但策略判斷與問題定義更重要。"],
["議題","Which is more important, data or creativity?","數據和創意哪個重要？","二選一陷阱。","I do not see them as opposites. Data can show what is happening and help evaluate results, while creativity creates new possibilities to test. Good marketing needs both.","我不把兩者看成對立。數據幫助理解現況與評估結果，創意創造新的可測試可能，好的行銷需要兩者。","What if they conflict?","I would go back to the objective, check the evidence, and design a test when possible.","衝突怎麼辦？回到目標、檢查證據，能測試就測試。"],
["議題","How would you measure the success of a marketing campaign?","如何衡量活動成功？","商業案例常見題。","I would start with the original objective, choose a primary KPI and supporting metrics, and also consider cost and incremental impact when possible.","先回到原始目標，設定核心KPI與輔助指標，也考慮成本與可能的增量影響。","Is a high ROAS always good?","Not necessarily. It depends on attribution, scale, margin, incremental value, and the objective.","高ROAS一定好？不一定，還要看歸因、規模、毛利、增量與目標。"],
["議題","What is a recent marketing issue that interests you?","最近關注什麼行銷議題？","時事考古題。","I am interested in how generative AI is changing marketing work, especially the balance between faster content production and stronger needs for brand judgment, data governance, and performance validation.","我關注生成式AI如何改變行銷工作，尤其是內容變快後，品牌判斷、資料治理與成效驗證的重要性。","Can you give a real example?","I would use a recent case I have actually read and can explain rather than quote a number I cannot verify.","能舉真實案例？用自己真正讀過的近期案例，不亂報數字。"],
["壓力","Your academic background is not in business. Can you handle this program?","你不是商管背景，跟得上嗎？","跨領域壓力題。","My undergraduate major is different, but my work has gradually moved toward business decisions, including advertising performance, budgets, clients, cross-functional work, and marketing planning. I also know I need stronger academic foundations, which is why I am applying.","大學科系不同，但工作已逐步走向廣告成效、預算、客戶、跨部門與行銷決策；我也知道自己需要更扎實的學術基礎。","Will you struggle with statistics?","It will be challenging, but I already work with performance data and I am preparing the basic concepts systematically.","統計會跟不上？有挑戰，但已有數據基礎，也正系統準備。"],
["壓力","Your research idea does not sound very innovative. What do you think?","你的研究好像不創新？","研究高壓題。","That is a valid concern. My expected contribution is to examine whether existing participation patterns change the effectiveness of relationship strategies. However, I would not claim novelty before a thorough literature review. If prior studies already answer the question well, I should refine it.","這是合理質疑。預期切入點是既有參與型態是否改變關係策略效果，但完整文獻回顧前不應先宣稱創新；若已有完整答案就應調整。","So your proposal is not mature?","It is a researchable direction at this stage, and I know which concepts still need refinement.","所以計畫不成熟？目前已有可研究方向，也知道哪些概念仍需收斂。"],
["壓力","If you are admitted to several schools, how will you choose?","如果多校錄取怎麼選？","敏感考古題。","I would compare research fit, faculty expertise, curriculum, and the learning environment that best supports my long-term goals. I would not decide only by ranking.","我會比較研究適配、師資、課程與學習環境，不會只看排名。","Are we your first choice?","I would answer honestly and explain the specific reasons this program fits my goals.","我們是第一志願？誠實回答並說明該所具體適配原因。"],
["臨場","Could you explain that in another way?","可以換個方式說嗎？","測試是否只會背稿。","Sure. In simpler terms, I want to understand the reason behind a result, not just repeat a method that worked before.","更簡單地說，我想理解結果背後的原因，而不是只重複以前有效的方法。","Can you give me an example?","For example, the same creative may perform differently for different audiences.","能舉例？同一素材對不同受眾可能有不同表現。"],
["臨場","I don't agree with your answer. Can you defend your position?","我不同意，你能辯護嗎？","英文壓力追問。","I understand there may be another perspective. My current view is based on evidence and context. If there is stronger evidence against my view, I would be willing to revise it.","我理解可能有其他觀點。我目前的看法建立在證據與情境上；若有更強反證，我願意修正。","So you are not confident?","Being willing to revise a view does not mean I have no position. It means I want my position to be evidence-based.","所以沒自信？願意修正不等於沒立場，而是希望立場有證據。"],
["臨場","What would you do if you did not understand an English question?","英文題聽不懂怎麼辦？","實戰生存題。","I would not guess. I would politely ask the professor to repeat or clarify: 'I'm sorry, could you please repeat the question?' or 'If I understand correctly, you're asking about my research method, right?'","我不會亂猜，而會禮貌請教授重複或確認問題。","Could you give another clarification phrase?","Do you mean that you would like me to explain the practical contribution?","另一句確認？Do you mean that you would like me to explain...?"]
);